function Write_TDF3_GNUPLOT(filename::String, TDF_Erange::Vector{Float64})

    gnu_file = open("$(filename)_TDF3.plt", "w")
    println(gnu_file, "# set terminal postscript eps enhanced color")
    println(gnu_file, "set size 1,1")
    println(gnu_file, "")
    println(gnu_file, "set xlabel font \"Arial,15\"")
    println(gnu_file, "set ylabel font \"Arial,15\"")
    println(gnu_file, "set tics font \"Arial, 10\"")
    println(gnu_file, "set xlabel 'Energy (eV)'")
    println(gnu_file, "set ylabel 'Dos (eV^{-1})'")
    println(gnu_file, "")
    println(gnu_file, "set xlabel offset 0,0")
    println(gnu_file, "set ylabel offset -2,0")
    println(gnu_file, "set lmargin 12")
    println(gnu_file, "set bmargin 2")
    println(gnu_file, "")
    println(gnu_file, "set ytics 0.2")
    println(gnu_file, "set title font \"Arial, 20\"")
    println(gnu_file, "unset key")
    println(gnu_file, "set grid")
    println(gnu_file, "")
    println(gnu_file, "# ymax = 1.0")
    println(gnu_file, "")
    println(gnu_file, "set xra [$(Dos_ErTDF_Erangeange[1]):$(TDF_Erange[2])]")
    println(gnu_file, "# set yra [0.0:ymax]")
    println(gnu_file, "set size 1")
    println(gnu_file, "plot \"$(filename)_TDF3.dat\" using 1:2 with lines linewidth 3")
    println(gnu_file, "")
    println(gnu_file, "set term pdf size 5in, 4in")
    println(gnu_file, "set output \"$(filename)_TDF3.pdf\"")
    println(gnu_file, "replot")
    close(gnu_file)
end


function Write_TDF4_GNUPLOT(filename::String, TDF_Erange::Vector{Float64})

    gnu_file = open("$(filename)_TDF4.plt", "w")
    println(gnu_file, "# set terminal postscript eps enhanced color")
    println(gnu_file, "set size 1,1")
    println(gnu_file, "")
    println(gnu_file, "set xlabel font \"Arial,15\"")
    println(gnu_file, "set ylabel font \"Arial,15\"")
    println(gnu_file, "set tics font \"Arial, 10\"")
    println(gnu_file, "set xlabel 'Energy (eV)'")
    println(gnu_file, "set ylabel 'Dos (eV^{-1})'")
    println(gnu_file, "")
    println(gnu_file, "set xlabel offset 0,0")
    println(gnu_file, "set ylabel offset -2,0")
    println(gnu_file, "set lmargin 12")
    println(gnu_file, "set bmargin 2")
    println(gnu_file, "")
    println(gnu_file, "set ytics 0.2")
    println(gnu_file, "set title font \"Arial, 20\"")
    println(gnu_file, "unset key")
    println(gnu_file, "set grid")
    println(gnu_file, "")
    println(gnu_file, "# ymax = 1.0")
    println(gnu_file, "")
    println(gnu_file, "set xra [$(TDF_Erange[1]):$(TDF_Erange[2])]")
    println(gnu_file, "# set yra [0.0:ymax]")
    println(gnu_file, "set size 1")
    println(gnu_file, "plot \"$(filename)_TDF3.dat\" using 1:2 with lines linewidth 3")
    println(gnu_file, "")
    println(gnu_file, "set term pdf size 5in, 4in")
    println(gnu_file, "set output \"$(filename)_TDF4.pdf\"")
    println(gnu_file, "replot")
    close(gnu_file)
end


function Write_TDF6_GNUPLOT(filename::String, TDF_Erange::Vector{Float64})

    gnu_file = open("$(filename)_TDF6.plt", "w")
    println(gnu_file, "# set terminal postscript eps enhanced color")
    println(gnu_file, "set size 1,1")
    println(gnu_file, "")
    println(gnu_file, "set xlabel font \"Arial,15\"")
    println(gnu_file, "set ylabel font \"Arial,15\"")
    println(gnu_file, "set tics font \"Arial, 10\"")
    println(gnu_file, "set xlabel 'Energy (eV)'")
    println(gnu_file, "set ylabel 'Dos (eV^{-1})'")
    println(gnu_file, "")
    println(gnu_file, "set xlabel offset 0,0")
    println(gnu_file, "set ylabel offset -2,0")
    println(gnu_file, "set lmargin 12")
    println(gnu_file, "set bmargin 2")
    println(gnu_file, "")
    println(gnu_file, "set ytics 0.2")
    println(gnu_file, "set title font \"Arial, 20\"")
    println(gnu_file, "unset key")
    println(gnu_file, "set grid")
    println(gnu_file, "")
    println(gnu_file, "# ymax = 1.0")
    println(gnu_file, "")
    println(gnu_file, "set xra [$(TDF_Erange[1]):$(TDF_Erange[2])]")
    println(gnu_file, "# set yra [0.0:ymax]")
    println(gnu_file, "set size 1")
    println(gnu_file, "plot \"$(filename)_TDF6.dat\" using 1:2 with lines linewidth 3")
    println(gnu_file, "")
    println(gnu_file, "set term pdf size 5in, 4in")
    println(gnu_file, "set output \"$(filename)_TDF6.pdf\"")
    println(gnu_file, "replot")
    close(gnu_file)
end


function Write_Sigma_GNUPLOT(filename::String, Erange::Vector{Float64}, Temp)

    gnu_file = open("$(filename)_sigma.plt", "w")
    println(gnu_file, "# set terminal postscript eps enhanced color")
    println(gnu_file, "set size 1,1")
    println(gnu_file, "")
    println(gnu_file, "set xlabel font \"Arial,13\"")
    println(gnu_file, "set ylabel font \"Arial,13\"")
    println(gnu_file, "set tics font \"Arial, 11\"")
    println(gnu_file, "set xlabel 'E - E_{F} (eV)'")
    println(gnu_file, "set ylabel '{/Symbol s}_{xx} (10^{6}/{/Symbol W}m)'")
    println(gnu_file, "")
    println(gnu_file, "set xlabel offset 0,0")
    println(gnu_file, "set ylabel offset -2,0")
    println(gnu_file, "set lmargin 12")
    println(gnu_file, "set bmargin 2")
    println(gnu_file, "")
    println(gnu_file, "# set ytics 0.1")
    println(gnu_file, "set title font \"Arial, 20\"")
    println(gnu_file, "# unset key")
    println(gnu_file, "set grid")
    println(gnu_file, "")
    println(gnu_file, "# ymax = 1.0")
    println(gnu_file, "")
    println(gnu_file, "set xra [$(Erange[1]):$(Erange[2])]")
    println(gnu_file, "# set yra [0.0:ymax]")
    println(gnu_file, "set size 1")
    println(gnu_file, "plot \"$(filename)_sigma$(Temp).dat\" using 1:(\$2*10**(-6)) with lines linewidth 3 title \"xx\"")
    println(gnu_file, "# replot \"$(filename)_sigma$(Temp).dat\" using 1:(\$3*10**(-6)) with lines linewidth 3 title \"yy\"")
    println(gnu_file, "# replot \"$(filename)_sigma$(Temp).dat\" using 1:(\$4*10**(-6)) with lines linewidth 3 title \"zz\"")
    println(gnu_file, "")
    println(gnu_file, "set term pdf size 5in, 4in")
    println(gnu_file, "set output \"$(filename)_sigma$(Temp).pdf\"")
    println(gnu_file, "replot")
    close(gnu_file)
end

#=
function Write_SigmaS_GNUPLOT(filename::String, Erange::Vector{Float64}, Temp)

    gnu_file = open("$(filename)_sigma.plt", "w")
    println(gnu_file, "# set terminal postscript eps enhanced color")
    println(gnu_file, "set size 1,1")
    println(gnu_file, "")
    println(gnu_file, "set xlabel font \"Arial,15\"")
    println(gnu_file, "set ylabel font \"Arial,15\"")
    println(gnu_file, "set tics font \"Arial, 10\"")
    println(gnu_file, "set xlabel '{/Symbol m} (eV)'")
    println(gnu_file, "# set ylabel '{/Symbol t}^{-1}sigmaxx (e^2/h)'")
    println(gnu_file, "")
    println(gnu_file, "set xlabel offset 0,0")
    println(gnu_file, "set ylabel offset -2,0")
    println(gnu_file, "set lmargin 12")
    println(gnu_file, "set bmargin 2")
    println(gnu_file, "")
    println(gnu_file, "# set ytics 0.1")
    println(gnu_file, "set title font \"Arial, 20\"")
    println(gnu_file, "# unset key")
    println(gnu_file, "set grid")
    println(gnu_file, "")
    println(gnu_file, "# ymax = 1.0")
    println(gnu_file, "")
    println(gnu_file, "set xra [$(Erange[1]):$(Erange[2])]")
    println(gnu_file, "# set yra [0.0:ymax]")
    println(gnu_file, "set size 1")
    println(gnu_file, "plot \"$(filename)_sigmas$(Temp).dat\" using 1:2 with lines linewidth 3 title \"x\"")
    println(gnu_file, "# replot \"$(filename)_sigmas$(Temp).dat\" using 1:3 with lines linewidth 3 title \"y\"")
    println(gnu_file, "# replot \"$(filename)_sigmas$(Temp).dat\" using 1:4 with lines linewidth 3 title \"z\"")
    println(gnu_file, "")
    println(gnu_file, "set term pdf size 5in, 4in")
    println(gnu_file, "set output \"$(filename)_sigmas$(Temp).pdf\"")
    println(gnu_file, "replot")
    close(gnu_file)
end
=#


function Write_Seebeck_2D_GNUPLOT(filename::String, Erange::Vector{Float64}, Temp)

    gnu_file = open("$(filename)_seebeck2D.plt", "w")
    println(gnu_file, "# set terminal postscript eps enhanced color")
    println(gnu_file, "set size 1,1")
    println(gnu_file, "")
    println(gnu_file, "set xlabel font \"Arial,13\"")
    println(gnu_file, "set ylabel font \"Arial,13\"")
    println(gnu_file, "set tics font \"Arial, 11\"")
    println(gnu_file, "set xlabel 'E - E_{F} (eV)'")
    println(gnu_file, "set ylabel 'S_{xx} (10^{-6}V/K)'")
    println(gnu_file, "")
    println(gnu_file, "set xlabel offset 0,0")
    println(gnu_file, "set ylabel offset -2,0")
    println(gnu_file, "set lmargin 12")
    println(gnu_file, "set bmargin 2")
    println(gnu_file, "")
    println(gnu_file, "# set ytics 0.1")
    println(gnu_file, "set title font \"Arial, 20\"")
    println(gnu_file, "# unset key")
    println(gnu_file, "set grid")
    println(gnu_file, "")
    println(gnu_file, "# ymax = 1.0")
    println(gnu_file, "")
    println(gnu_file, "set xra [$(Erange[1]):$(Erange[2])]")
    println(gnu_file, "# set yra [0.0:ymax]")
    println(gnu_file, "set size 1")
    println(gnu_file, "plot \"$(filename)_seebeck2D$(Temp).dat\" using 1:(\$2*10**6) with lines linewidth 3 title \"xx\"")
    println(gnu_file, "# replot \"$(filename)_seebeck2D$(Temp).dat\" using 1:(\$3*10**6) with lines linewidth 3 title \"xy\"")
    println(gnu_file, "# replot \"$(filename)_seebeck2D$(Temp).dat\" using 1:(\$4*10**6) with lines linewidth 3 title \"yx\"")
    println(gnu_file, "# replot \"$(filename)_seebeck2D$(Temp).dat\" using 1:(\$5*10**6) with lines linewidth 3 title \"yy\"")
    println(gnu_file, "")
    println(gnu_file, "set term pdf size 5in, 4in")
    println(gnu_file, "set output \"$(filename)_seebeck2D$(Temp).pdf\"")
    println(gnu_file, "replot")
    close(gnu_file)
end


function Write_Seebeck_3D_GNUPLOT(filename::String, Erange::Vector{Float64}, Temp)

    gnu_file = open("$(filename)_seebeck3D.plt", "w")
    println(gnu_file, "# set terminal postscript eps enhanced color")
    println(gnu_file, "set size 1,1")
    println(gnu_file, "")
    println(gnu_file, "set xlabel font \"Arial,15\"")
    println(gnu_file, "set ylabel font \"Arial,15\"")
    println(gnu_file, "set tics font \"Arial, 10\"")
    println(gnu_file, "set xlabel 'E - E_{F} (eV)'")
    println(gnu_file, "set ylabel 'S_{xx} (10^{-6}V/K)'")
    println(gnu_file, "")
    println(gnu_file, "set xlabel offset 0,0")
    println(gnu_file, "set ylabel offset -2,0")
    println(gnu_file, "set lmargin 12")
    println(gnu_file, "set bmargin 2")
    println(gnu_file, "")
    println(gnu_file, "# set ytics 0.1")
    println(gnu_file, "set title font \"Arial, 20\"")
    println(gnu_file, "# unset key")
    println(gnu_file, "set grid")
    println(gnu_file, "")
    println(gnu_file, "# ymax = 1.0")
    println(gnu_file, "")
    println(gnu_file, "set xra [$(Erange[1]):$(Erange[2])]")
    println(gnu_file, "# set yra [0.0:ymax]")
    println(gnu_file, "set size 1")
    println(gnu_file, "plot \"$(filename)_seebeck3D$(Temp).dat\" using 1:(\$2*10**6) with lines linewidth 3 title \"xx\"")
    println(gnu_file, "# replot \"$(filename)_seebeck3D$(Temp).dat\" using 1:(\$3*10**6) with lines linewidth 3 title \"xy\"")
    println(gnu_file, "# replot \"$(filename)_seebeck3D$(Temp).dat\" using 1:(\$4*10**6) with lines linewidth 3 title \"xz\"")
    println(gnu_file, "# replot \"$(filename)_seebeck3D$(Temp).dat\" using 1:(\$5*10**6) with lines linewidth 3 title \"yx\"")
    println(gnu_file, "# replot \"$(filename)_seebeck3D$(Temp).dat\" using 1:(\$6*10**6) with lines linewidth 3 title \"yy\"")
    println(gnu_file, "# replot \"$(filename)_seebeck3D$(Temp).dat\" using 1:(\$7*10**6) with lines linewidth 3 title \"yz\"")
    println(gnu_file, "# replot \"$(filename)_seebeck3D$(Temp).dat\" using 1:(\$8*10**6) with lines linewidth 3 title \"zx\"")
    println(gnu_file, "# replot \"$(filename)_seebeck3D$(Temp).dat\" using 1:(\$9*10**6) with lines linewidth 3 title \"zy\"")
    println(gnu_file, "# replot \"$(filename)_seebeck3D$(Temp).dat\" using 1:(\$10*10**6) with lines linewidth 3 title \"zz\"")
    println(gnu_file, "")
    println(gnu_file, "set term pdf size 5in, 4in")
    println(gnu_file, "set output \"$(filename)_seebeck3D$(Temp).pdf\"")
    println(gnu_file, "replot")
    close(gnu_file)
end

#=
function Write_Kappa_GNUPLOT(filename::String, Erange::Vector{Float64})

    gnu_file = open("$(filename)_sigma.plt", "w")
    println(gnu_file, "# set terminal postscript eps enhanced color")
    println(gnu_file, "set size 1,1")
    println(gnu_file, "")
    println(gnu_file, "set xlabel font \"Arial,15\"")
    println(gnu_file, "set ylabel font \"Arial,15\"")
    println(gnu_file, "set tics font \"Arial, 10\"")
    println(gnu_file, "set xlabel '{/Symbol m} (eV)'")
    println(gnu_file, "# set ylabel '{/Symbol t}^{-1}sigmaxx (e^2/h)'")
    println(gnu_file, "")
    println(gnu_file, "set xlabel offset 0,0")
    println(gnu_file, "set ylabel offset -2,0")
    println(gnu_file, "set lmargin 12")
    println(gnu_file, "set bmargin 2")
    println(gnu_file, "")
    println(gnu_file, "# set ytics 0.1")
    println(gnu_file, "set title font \"Arial, 20\"")
    println(gnu_file, "# unset key")
    println(gnu_file, "set grid")
    println(gnu_file, "")
    println(gnu_file, "# ymax = 1.0")
    println(gnu_file, "")
    println(gnu_file, "set xra [$(Erange[1]):$(Erange[2])]")
    println(gnu_file, "# set yra [0.0:ymax]")
    println(gnu_file, "set size 1")
    println(gnu_file, "plot \"$(filename)_kappa.dat\" using 1:2 with lines linewidth 3 title \"xx\"")
    println(gnu_file, "# replot \"$(filename)_kappa.dat\" using 1:3 with lines linewidth 3 title \"y\"")
    println(gnu_file, "# replot \"$(filename)_kappa.dat\" using 1:4 with lines linewidth 3 title \"z\"")
    println(gnu_file, "")
    println(gnu_file, "set term pdf size 5in, 4in")
    println(gnu_file, "set output \"$(filename)_kappa.pdf\"")
    println(gnu_file, "replot")
    close(gnu_file)
end
=#
